services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: strava_titan
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d strava_titan"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    environment:
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/strava_titan
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - WEBHOOK_CALLBACK_URL=${WEBHOOK_CALLBACK_URL}
      - VERIFICATION_TOKEN=${VERIFICATION_TOKEN}
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1 #https://stackoverflow.com/questions/59812009/what-is-the-use-of-pythonunbuffered-in-docker-file
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./scripts:/scripts
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend/stravatitan
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/stravatitan:/app
      - /app/node_modules
    depends_on:
      - backend